POST http://localhost:8000/api/user/register
Content-Type: application/json

{
    "name": "Miya Marselina",
    "email": "miyamarselina@gmail.com",
    "password": "teddy123"
}

###

POST http://localhost:8000/api/user/register
Content-Type: application/json

{
    "name": "Super Admin",
    "email": "adminsuper@gmail.com",
    "password": "teddy123",
    "isSuperuser": true
}

###

POST http://localhost:8000/api/user/login
Content-Type: application/json

{
    "email": "adminsuper@gmail.com",
    "password": "teddy123"
}

###

POST http://localhost:8000/api/user/login
Content-Type: application/json

{
    "email": "miyamarselina@gmail.com",
    "password": "teddy123"
}

###

POST http://localhost:8000/api/lecture/create
Content-Type: application/json

{
    "moduleNumber": 1,
	"name": "Low Pass Filter",
	"title": "Teori 1",
	"description": "dasdawdasdasdawdad asdawdasdasdawd  dasdawdasdasdawd asasdawdsasdgfgjhg",
	"imageUrl": "Image/Url",
	"modelAR": "Model/AR",
	"tags": ["Filter RC", "HPF"]
}

###

POST http://localhost:8000/api/lecture/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VwZXIgQWRtaW4iLCJlbWFpbCI6ImFkbWluc3VwZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkMkoxbzhiZ1FJZS9qQXVNbWZDT3NDZVAuMlBqTkl2Q01ZTjJxY2YxTnVVMzFzMzA1Z096REsiLCJkYXRlIjoiMjAyMi0wNS0yMVQxMzozMzo1My4wNDVaIiwiaXNTdXBlcnVzZXIiOnRydWUsIl9fdiI6MCwiaWQiOiI2Mjg4ZWE1OWIwOTgzOWFmN2IyNTcyMzYiLCJpYXQiOjE2NTMzNjI4NjZ9.q1tFBsFYvogUaZrwnDklgSDch8teNxOLYWQvRoie7qc

{
    "moduleNumber": 2,
	"name": "High Pass Filter",
	"title": "Teori 2",
	"description": "dasdawdasdasdawdad asdawdasdasdawd  dasdawdasdasdawd asasdawdsasdgfgjhg",
	"imageUrl": "Image/Url",
	"modelAR": "Model/AR",
	"tags": ["Filter LR", "HPF"]
}

###

PUT http://localhost:8000/api/lecture/6288ebb3658ae08ad2934392/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VwZXIgQWRtaW4iLCJlbWFpbCI6ImFkbWluc3VwZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkMkoxbzhiZ1FJZS9qQXVNbWZDT3NDZVAuMlBqTkl2Q01ZTjJxY2YxTnVVMzFzMzA1Z096REsiLCJkYXRlIjoiMjAyMi0wNS0yMVQxMzozMzo1My4wNDVaIiwiaXNTdXBlcnVzZXIiOnRydWUsIl9fdiI6MCwiaWQiOiI2Mjg4ZWE1OWIwOTgzOWFmN2IyNTcyMzYiLCJpYXQiOjE2NTMzNjI4NjZ9.q1tFBsFYvogUaZrwnDklgSDch8teNxOLYWQvRoie7qc

{
    "moduleNumber": 2,
	"name": "Band Pass Filter",
	"title": "Lab 2",
	"description": "============= asdawdasdasdawd  dasdawdasdasdawd asasdawdsasdgfgjhg",
	"imageUrl": "Image/Url",
	"modelAR": "Model/AR",
	"tags": ["Filter LR", "BPF"]
}

### GET Single Lecture

GET http://localhost:8000/api/lecture/6288ecd963a105913189900a

### GET All Lectures
GET http://localhost:8000/api/lecture/

### DELETE Single Lecture
DELETE http://localhost:8000/api/lecture/6288ebb3658ae08ad2934392


### GET All Lectures
GET http://localhost:8000/api/lecture/favorite
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGY0NzUwYWQyODUxN2U0OWI5NDA4YSIsIm5hbWUiOiJUZWRkeSBSYWhzeWFoIiwiaWF0IjoxNjUzNTc1ODU1LCJleHAiOjE2NTM1NzU4NzB9.ba0R--TuOYMQGFOk1-pKXkyKWH9hBD5XB2svND65XVk

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVkZHkgUmFoc3lhaCIsImVtYWlsIjoidGVkZHlyYWhzeWFoQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJFd5R0dNS2p5ZHFFMm9rRzFuQVRnSC4wcGJoUFFCV2VWMjBYNUhPUUkzek5aNGxka2I5aFVHIiwiZGF0ZSI6IjIwMjItMDUtMjZUMDk6MTk6MDguNTU1WiIsImlzU3VwZXJ1c2VyIjp0cnVlLCJfX3YiOjAsImlkIjoiNjI4ZjQ3NTBhZDI4NTE3ZTQ5Yjk0MDhhIiwiaWF0IjoxNjUzNTc2MDMwfQ.8XH8gBXwuHwatfVDmTMZMeVZzKlEffbMOlbcwlRGCJg"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "teddyrahsyah@gmail.com",
    "password": "teddy123"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVkZHkgUmFoc3lhaCIsImVtYWlsIjoidGVkZHlyYWhzeWFoQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJFd5R0dNS2p5ZHFFMm9rRzFuQVRnSC4wcGJoUFFCV2VWMjBYNUhPUUkzek5aNGxka2I5aFVHIiwiZGF0ZSI6IjIwMjItMDUtMjZUMDk6MTk6MDguNTU1WiIsImlzU3VwZXJ1c2VyIjp0cnVlLCJfX3YiOjAsImlkIjoiNjI4ZjQ3NTBhZDI4NTE3ZTQ5Yjk0MDhhIiwiaWF0IjoxNjUzNTc2MDMwfQ.8XH8gBXwuHwatfVDmTMZMeVZzKlEffbMOlbcwlRGCJg"
}