/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('modelFilter.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
        <group position={[0.1, 0.33, 0.19]} rotation={[0, Math.PI / 2, 0]} scale={0.1}>
            <mesh geometry={nodes.Roundcube004.geometry} material={materials['body resistor']} />
            <mesh geometry={nodes.Roundcube004_1.geometry} material={materials['kaki resistor']} />
            <mesh geometry={nodes.Roundcube004_2.geometry} material={materials.nilai} />
            <mesh geometry={nodes.Roundcube004_3.geometry} material={materials['nilai 2']} />
        </group>
        <mesh geometry={nodes.Cube.geometry} material={materials['pcb board']} position={[0.03, 0, 0.19]} scale={[0.1, 0.2, 0.3]} />
        <group position={[0.11, 0.37, 0.55]} rotation={[0, Math.PI / 2, 0]} scale={0.1}>
            <mesh geometry={nodes.Cube002.geometry} material={materials['body kapasitor']} />
            <mesh geometry={nodes.Cube002_1.geometry} material={materials['kaki kapasitor']} />
        </group>
        </group>
    )
}

useGLTF.preload('/modelFilter.gltf')
